### ISSUE TITLE
Observers are undefined after upgrading to 1.11

### ISSUE THREAD

**Issue by QuantumInformation** [emberjs/ember.js#10825]
Hi, I just upgraded to 1.11 and now all my observers are undefined, resulting in the error:

`Uncaught TypeError: undefined is not a function
`
package:
```js
{
  "name": "ember-cli-test-recorder",
  "version": "0.0.0",
  "description": "The default blueprint for ember-cli addons.",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.2",
    "ember-cli": "0.2.2",
    "ember-cli-app-version": "0.3.3",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "0.0.8",
    "ember-cli-htmlbars": "0.7.4",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.9",
    "ember-cli-uglify": "1.0.1",
    "ember-data": "1.0.0-beta.16.1",
    "ember-export-application-global": "^1.0.2",
    "ember-disable-prototype-extensions": "^1.0.0"
  },
  "keywords": [
    "ember-addon"
  ],
  "dependencies": {
    "ember-cli-babel": "^4.0.0"
  },
  "ember-addon": {
    "configPath": "tests/dummy/config"
  }
}
```
bower:
```js
{
  "name": "ember-cli-test-recorder",
  "dependencies": {
    "jquery": "^1.11.1",
    "ember": "1.11.0",
    "ember-data": "1.0.0-beta.16.1",
    "ember-resolver": "~0.1.15",
    "loader.js": "ember-cli/loader.js#3.2.0",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.0.2",
    "ember-qunit": "0.3.0",
    "ember-qunit-notifications": "0.0.7",
    "qunit": "~1.17.1"
  }
}
```

**Comment by QuantumInformation** [comment]
Sorry, I just noticed I had to add this:
`EmberENV.EXTEND_PROTOTYPES = { String: false, Array: true };`

**Comment by stefanpenner** [comment]
Ember addons now disable prototype extensions. So that users of the addons can use it regardless of if they have extensions on or off.  You should leave them off for addons.

Also just so people are aware this was a change in ember cli not in ember. We found that most addons forced people into extends prototype true and we wanted to ensure addons by default enforced something every could use.
