### ISSUE TITLE
Ember helpers don't seem to work in 1.13

### ISSUE THREAD

**Issue by stevesims** [emberjs/ember.js#11870]
I've tried creating an ember helper using `ember generate helper test-helper`, made the generated code just return a simple string, and then attempted to use `{{test-helper}}` inside a template.  Unfortunately though the template render fails, with an `Uncaught TypeError: fn.apply is not a function` occurring inside a function called `helperFunction` inside `HandlebarsCompatibleHelper`.

**Comment by rwjblue** [comment]
Questions:

* What Ember version (the result of `Ember.VERSION`)?
* What Ember CLI version (the result of `ember version`)?
* What is the contents of the `app/helpers/test-helper.js`?

**Comment by stevesims** [comment]
Ember version 1.13.5, Ember CLI 1.13.1.

app/helpers/test-helper.js is:
```js
import Ember from 'ember';

export function testHelper(params/*, hash*/) {
  return 'test Thing!!!';
}

export default Ember.Helper.helper(testHelper);
```

**Comment by stevesims** [comment]
Ember version is actually the latest github master

**Comment by sheldonnbbaker** [comment]
I'm experience the same issue with the exact same version numbers.=
I'm calling the helper as part of a component, like so:
```{{my-component name=(full-name model.firstName "Smith")}}```

**Comment by pixelhandler** [comment]
@stevesims do you think you can create a jsbin, jsfiddle or http://ember-twiddle.com example? ( links here: https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#reporting-a-bug )

**Comment by rwjblue** [comment]
This seems to be working properly, demo: http://ember-twiddle.com/0fbd9eb769c048e048ea

Closing this issue for now, but will happily reopen with a reproduction.

**Comment by stevesims** [comment]
sorry @pixelhandler I didn't get a chance to create a twiddle, and thanks @rwjblue for doing so.

On further investigation of my code, it seems that my problem was caused by a component that includes an (internal) dependency of ember-cli-auto-register-helpers.  Once that was removed my error went away, but everything continued to work just fine.

@sheldonnbbaker it might be worth having a trawl to see if this is also your problem.  Whilst the latest version of ember-cli-auto-register-helpers has code to disable it's behaviour for Ember 2, things remain broken on Ember 1.13.

**Comment by rwjblue** [comment]
> Whilst the latest version of ember-cli-auto-register-helpers has code to disable it's behaviour for Ember 2, things remain broken on Ember 1.13.

@stevesims - That was fixed with https://github.com/stefanpenner/ember-cli-auto-register-helpers/pull/6, but it doesn't seem like it has been released yet.  Maybe create an issue over there asking for a release?
