### PR TITLE
Upgrade glimmer-vm to latest

### PR DESCRIPTION
**Pull request by smfoote**
There is much left to do here. This is just the first pass, where I have
done nothing but try to clear out the errors caused by the upgrade. Not
all of the errors are cleared yet, largely because several exports from
glimmer-vm have been removed and I don't know how to replace them (help
wanted). Below is a list of the needed changes and problems I have
encountered in the upgrade process.

### UPGRADE NOTES (starting at glimmer-vm 0.25.6)

* Simple is now in @glimmer/interfaces
* ComponentManager.getSelf cannot return null (returns RootReference?)
* ComponentManager.getTag returns ComponentStateBucket.tag (: Tag)
* Some code moved from ComponentManager.update to
* ComponentManager.didUpdate
* ComponentManager<ComponentStateBucket> -->
* ComponentManager<ComponentStateBucket, ComponentDefinition>
* ComponentManager.create signature changed
* ComponentStateBucket's defintion is now DefinitionState instead of
* ComponentDefinition
* ComponentManager.prepareArgs signature changed
* ComponentManager.getCapabilities is new
* CompiledDynamicTemplate is gone (no longer in runtime, anyway) see
* https://github.com/glimmerjs/glimmer-vm/commit/79f2b4521f5a7d48d04e3fd34e224ddf5bc4c241#diff-d561208b0ad153d9273c2188e16c7442
* Must implicitly include @glimmer/vm and @glimmer/opcode-compiler and
* @glimmer/encoder in ember-cli-build.js
* compileLayout -> scanLayout -> prepareLayout -> new WrappedBuilder
* isSafeString is no longer exported publicly. Is that intentional?
* normalizeTextValue is no longer exported publicly. Is that
* intentional?
* isComponentDefinition is gone, kind of replaced by
* `isCurriedComponentDefinition`. Neither is exported.
* getComponentDefintion is no longer part of Environment.
* referenceFromParts has been removed.
* f3444e9ae0c7751047bdcd856e61344bfb548e12
* readDOMAttr has been removed. 316805b9175e01698120b9566ec51c88d075026a

### CODE REVIEW

**Comment by rwjblue** [comment]
FYI - I am working on fixing the conflicts introduced by #16000 and #16001...

**Comment by smfoote** [comment]
Tests that are still failing:

- [ ] engine rendering tests (6 tests failing because `mount is not a helper`)
- [ ] contextual components (11 tests failing. Curried positional params are now handled by glimmer-vm. Need to decide if they are working as they should. If so, updated the tests. See #15287)
- [ ] curly components (8 tests failing due to `hasBlockParams` not working as expected)
- [ ] dynamic components (2 tests failing. Cause unknown)
- [ ] link-to (17 tests failing because outlet is using the wrong kind of reference for `getSelf`. Should be RootReference)
- [ ] view tree (2 tests failing. Cause unknown)
- [ ] dynamic content (2 tests failing. type errors)
- [ ] inline styles (6 tests failing due to lack of the style warning)
- [ ]  custom helpers (5 tests failing - Ember.assert not being called or not being called with the right text)
- [ ] element action (2 tests failing: `Compile Error action is not a modifier: Helpers may not be used in the element form`)
- [ ] {{input}} (3 tests failing: `TODO convert to component invoke`, instead of `dynamicComponentMacro`)
- [ ] {{render}} (21 tests failing because `render is not a helper`)
- [ ] {{mount}} (9 tests failing because `mount is not a helper`)
- [ ] Layout cache (3 tests failing because `this.env.getTemplate` is not a function. Need to use resolver instead, probably)
- [ ] Basic routing (11 tests failing, most because `builder.component.dynamic` is not a function. Need to switch to `builder.component.static`?)
- [ ] query params (14 tests failing. Query params are not updating. Looks like a reference problem.)

**Comment by rwjblue** [comment]
GREEEEEEEEEEEEEEEEEEEEEEEEENNNNNNNNNN!!!!!


screenshot of passing ci

**Comment by jonnii** [comment]
@rwjblue what does this mean for ember users?

**Comment by rwjblue** [comment]
Not much. Just a dependency update. 😃

**Comment by SergeAstapov** [comment]
@rwjblue does this update unblock rehydration for server-sider rendered apps?
If not - what else is blocking it unless "just needs to be done"?

**Comment by acorncom** [comment]
@SergeAstapov there was some initial discussion of this on the Fastboot Slack channel. Because yes, folks are interested in exploring that now ... 😀
