### ISSUE TITLE
Attempted to call .send() on the destroyed route

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#16778]
After upgrading to 3.2.0 I get hundreds of test failures, all seem to be related to use of `.send` and/or destroy/ing/ed objects.

I'm not sure what the problem is, but I have been able to create a twiddle of 1 such failing test. 

[Working test in 3.1.2](https://ember-twiddle.com/2450391f580b903599e779876c33ba08?openFiles=tests.acceptance.my-acceptance-test.js%2C&route=%2Ffoo)

[Failing test in 3.2.0](https://ember-twiddle.com/c48aed5df6fd266d04b1a80da498f2f0?openFiles=tests.acceptance.my-acceptance-test.js%2C&route=%2Ffoo)

There are other failures with similar messages, e.g
`Attempted to call .send() with the action 'showLayout' on the destroyed route 'error'`
`Attempted to call .send() with the action \'_updated\' on the destroyed object`
`this.get(...).addObject is not a function` (although, tbf this one might be a separate issue)

**Comment by rwjblue** [comment]
The issue here is related to a combination of things:

1. the `deactivate` hook is called while the router hierarchy is being destroyed
2. an assertion was added when calling `.send` / `.sendAction` on destroyed objects

A quick workaround (in the twiddle) would be modifying the `deactivate` to something like:

```js
  deactivate() {
    if (!this.isDestroying) {
      this.send('showLayout');
    }
    this._super(...arguments);
  }
```

I think the correct fix would be (in the router), to avoid calling `deactivate` during teardown/reset.

**Comment by amk221** [comment]
Oh ok, so I have to implement something like `trySend` similar to `trySet`
