### PR TITLE
Implement Glimmer Engine

### PR DESCRIPTION
**Pull request by wycats**
Glimmer is the next-generation rendering engine for Ember.js. Built on top of HTMLBars, streams, and an entirely rewritten view layer, Glimmer offers the best performance of any of the major JavaScript frameworks while remaining backwards compatible with Ember 1.x apps.

---

The Virtual DOM showed the world that render-time diffing delivers awesome performance by minimizing DOM updates and keeping unchanged elements stable. But like any abstraction, it comes with a cost. In this case, constructing the virtual DOM to compare requires at least some subset of components do a full re-render, and building virtual DOM nodes for static areas of your markup that will never change for every change requires many more allocations and increases GC pressure.

Glimmer analyzes templates at compile time, relying on the fact that Handlebars' declarative syntax clearly differentiates between static areas, which make up the majority of a template, and the dynamic areas that can change. Instead of invoking a `render()` method and diffing the result, Glimmer only walks the (much smaller) existing dynamic tree.

---

Handlebars' declarative syntax means that from the perspective of an app, the template is being "re-rendered every time", but we can take advantage of static knowledge to reduce the work that we need to do. User code, like helpers and computed properties, are executed during the walk, but only to get (primitive) **values** which can be `===` compared, not to build up a new tree. **In other words, the programming model is equivalent to "render every time", but we take advantage of the declarative nature of Ember's APIs to reduce work**.

Internally, instead of creating a virtual DOM, Glimmer builds a tree of streams, each stream pointing to a node in the DOM. On initial render, we track the last value (always a primitive) that we inserted into the DOM. The streams are not exposed to application code; Glimmer executes user code when necessary and pushes the new value into the stream.

When re-rendering, we walk the tree and flush the streams. If the primitive value produced by the stream has not changed, we do nothing. If it has changed, we write the change to the DOM. **Like Virtual DOM approaches, this is a "write-only" algorithm**.

One of the benefits of this approach is that **we can naturally fuse the Ember/Polymer model of observing individual properties with the React model of explicitly re-rendering areas of the template**. No matter what happens, the process of revalidation walks the tree, looking for dirty nodes, and revalidates any dirty nodes it finds.

The only difference is how much of dynamic tree is marked dirty before revalidation begins. Also, because observation can only dirty dynamic nodes (and schedule a top-down revalidation), multiple observers and re-renders that occur during a single run-loop still only produce **a single batch of DOM updates**.

In essence, the biggest difference between Glimmer and traditional virtual DOM approaches is that we diff values, not DOM. This approach not only lets us avoid the algorithmic complexity of tree diffing (instead, we just `===` check two values), it also lets us avoid doing many render-time allocations.

[Slides from the talk at EmberConf](http://f.cl.ly/items/0t031v2Z3y001V1N0F3N/Virtual%20DOM.pdf)
### Work List

(this looks like more things than it actually is)
- [x] merge subscription change into our branch
- [x] linkRenderNode can mark stability
- [x] Ember should return true from `linkRenderNode`
- [x] make sure all child streams correctly disconnect from parents
- [x] add stream pruning logic that correctly prunes ancestors
- [x] add scope teardown hook to HTMLBars (recursive upon `clear` or `remove`)
  - [ ] this is also responsible for view layer teardown
- [x] Propagate correct visitor through descendent hooks (so dirty checks can be avoided for a subtree)
- [x] Do not dirty check render nodes that were just created (fixes regression)
- [x] Add "classify" hook to decide which hook `content` et al should delegate to
- [x] Make sure that #view is idempotent
- [x] Components and views should create a new scope frame
  - [x] Implement custom scope in Ember (so that ambient `view`, `controller`, etc. can be stored)
  - [x] Eliminate `*component*` hacks
- [x] Lifecycle hooks on the renderer
- [x] Move code duplicated between `#view`, `#component` and `Ember.View` into the Renderer
- [ ] Support reflecting attributes onto angle-bracket components
- [ ] Pass mutable bindings as "mutator" objects
- [ ] Support `foo={{action "bar"}}`
- [ ] Legacy support: Implement unknownProperty/setUnknownProperty to work with mutator objects
  - [ ] Deprecate setting non-`mut` attributes, and support `(mut foo)` sexprs in legacy Handlebars syntax
- [ ] Investigate executing teardown callbacks at a "quiescent" state ("vent plasma")
  - [ ] Make sure to consider the rpflo stress test situation
- [x] Implement a `zip` and `map` abstraction for streams to clean up ad hoc stream creation
- [ ] Add tests for memory leaks
- [ ] Make sure that custom render functions that mutate the buffer continue to work
- [ ] `options.template` should not exist if there is no template
- [ ] feature flag all the things
- [ ] Handlebars helper compat
- [ ] Template function that returns a string (legacy)
- [X] Context shifting `#each`
- [ ] `collection` helper
- [ ] `{{input}}`
  - [X] `TextField`
  - [X] `Checkbox`
  - [ ] `TextArea`
- [ ] `Ember.Select`
- [ ] `unbound`
  - [X] non-block form
  - [ ] block form (partially done, but not completely)
- [X] `#view` and `view` helper
- [ ] `#view` and `view` helper with back-compat edge cases
- [X] `#with` helper
- [ ] `with` helper with back-compat edge-cases
- [ ] `yield` without a block
- [ ] `{{render}}`
- [ ] `ContainerView`
- [X] Top-level view APIs
  - [X] `createElement`
  - [X] `appendTo`
  - [X] `replaceIn`
  - [ ] `destroyElement`
- [ ] `isVisible`

### CODE REVIEW

**Comment by wycats** [comment]
React Hook | Ember Hook | Server? | Initial Render? | Rerender? | Purpose
--- | --- | --- | --- | --- | ---
`componentWillMount` | `init` | Yes | Yes | No | Set initial component state without triggering re-render
`componentDidMount` | `didInsertElement` | No | Yes | No | Provides opportunity for manual DOM manipulation
`componentWillReceiveProps` | `willReceiveAttrs` | No | No | Yes | React to changes in component attributes, so that `setState` can be invoked before render
`shouldComponentUpdate` | Maybe N/A | No | No | Yes | Gives a component an opportunity to reject downstream revalidation
`componentWillUpdate` | `willUpdate` | No | No | Yes | Invoked before a template is re-rendered to give the component an opportunity to inspect the DOM before updates have been applied ([example](http://blog.vjeux.com/2013/javascript/scroll-position-with-react.html))
`componentDidUpdate` | `didUpdate` | No | No | Yes | Invoked after a template is re-rendered to give the component an opportunity to update the DOM ([example](http://blog.vjeux.com/2013/javascript/scroll-position-with-react.html))
`componentWillUnmount` | `willDestroyElement` | No | No | Yes | The inverse of `componentDidMount`/`didInsertElement`; clean up anything set up in that hook
[N/A](https://github.com/facebook/react/issues/2074) | `willRender` | No | Yes | Yes | In Ember, executed *both* after `init` and after `willUpdate`*
[N/A](https://github.com/facebook/react/issues/2074) | `didRender` | No | Yes | Yes | In Ember, executed *both* after `didInsertElement` and `didUpdate`*

* These hooks can be used in cases where the setup for initial render and subsequent re-renders is idempotent (e.g. `$().addClass`) instead of duplicating the logic in both places. In most cases, it is better to try to make these hooks idempotent, in keeping with the spirit of "re-render from scratch every time".

**Comment by wycats** [comment]
The above comment is an attempt to classify the hooks in React and Ember so that we can make sure that the new Ember components implement *at least* the hooks that React folks have identified as being important in the programming model.

**Comment by rwjblue** [comment]
All new API's will also need to be feature flagged.

**Comment by wycats** [comment]
@rwjblue yessir

**Comment by Linicks** [comment]
The init hook name is a little unclear compared to componentWillMount.  Could it be named initElelement, or something similar ?

**Comment by stefanpenner** [comment]
> The init hook name is a little unclear compared to componentWillMount. Could it be named initElelement, or something similar ?

I would prefer leaving it as init, as it clearly describes what it handles, initialization of the object. Which is the same between all ember objects, introducing a deviation here seems strange.

**Comment by stefanpenner** [comment]
@wycats @tomdale good job guys :)

**Comment by alexspeller** [comment]
:heart_eyes:

**Comment by alexdiliberto** [comment]
This is amazing :+1: :+1: :+1:

**Comment by Linicks** [comment]
The problem with just using init is that init is used in so many places in the tech world.  In an Ember only world it would be clear and concise, but in an ever increasing complex tech stack it's nice to have that extra bit of clarity.  I think that's why FB chose an even more verbose naming scheme than my proposal.  I have had the chance/misfortune of maintaining allot of legacy software, and appreciate when the code is self describeing as practical.  This is really a preference in either direction, but after being in this game for so many years I'm getting a little opionated :)  Either way this is exciting stuff, and look forward to seeing this come together in Ember.

**Comment by ebryn** [comment]
@Linicks if you look at their ES6 syntax, you'll see they're utilizing the constructor to initialize `this.state`

**Comment by fivetanley** [comment]
What is a "ShadowRoot"?

**Comment by gonvaled** [comment]
This being a "DOM write-only" implementation, how does ember deal with changes to the DOM done by third-party components, like jQuery based changes, which are not controlled by Ember?

**Comment by davidlormor** [comment]
"the Dynamic Tree only includes nodes that may have changed (...) and never needs to compare static content that will never change"...sounds fast! :rocket: :+1:

**Comment by stefanpenner** [comment]
> This being a "DOM write-only" implementation, how does Ember deal with changes to the DOM done by third-party components, like jQuery based changes, which are not controlled by Ember?

It doesn't and likely cannot support this.

**Comment by mgenev** [comment]
@stefanpenner that means we can no longer use bootstrap in an ember app unless a bootstrap-for-ember version is written, right? Same goes for foundation etc...

**Comment by stefanpenner** [comment]
> @stefanpenner that means we can no longer use bootstrap (jQiery dependent) in an ember app unless a bootstrap-for-ember version is written, right? Same goes for foundation etc...

No, this is no different then today. If you component is re-rendered your bootstrap and jquery code needs to re-run.

**Comment by wycats** [comment]
@stefanpenner @mgenev I think there's a little bit of confusion here.

From new-world Ember's perspective, as long as the element for a component still exists in the DOM, it doesn't matter where it has been moved, whether it has been decorated, etc.

There are a few restrictions on moving elements around, but they're very minor and would be easy to abstract. Stay tuned as we continue to make more progress.

File: packages/ember-htmlbars/tests/helpers/new_each_helper_test.js [hunk 1]
```diff
@@ -0,0 +1,334 @@
...
+
+import compile from "ember-template-compiler/system/compile";
+
+var people, view, registry, container;
+
+// This function lets us write {{#EACH|people|p}} {{p}} {{/each}}
+// and generate:
+//
+// - {{#each p in people}} (legacy)
+// - {{#each people as |p|}} (legacy)
```
Comment (ef4) [inline packages/ember-htmlbars/tests/helpers/new_each_helper_test.js]: why is `{{#each people as |p|}}` marked as legacy? Are we not keeping that syntax?

File: packages/ember-metal/lib/utils.js [hunk 2]
```diff
@@ -105,6 +105,14 @@ function intern(str) {
   return str;
 }
 
+export function symbol(debugName) {
+  // TODO: Investigate using platform symbols, but we do not
+  // want to require non-enumerability for this API, which
+  // would introduce a large cost.
+
+  return intern(debugName + ' [id=' + GUID_KEY + Math.floor(Math.random() * new Date()) + ']');
```
Comment (ef4) [inline packages/ember-metal/lib/utils.js]: Are there really platforms where Math.random() is so broken that we need to multiply by `new Date`?

Comment (tomdale) [inline packages/ember-metal/lib/utils.js]: Dunno, let's have our IE friends run http://jsbin.com/lexonidara/2/edit?html,js,output overnight.

Comment (tomdale) [inline packages/ember-metal/lib/utils.js]: Our rationale here was that `Math.random()` does not have cryptographically-guaranteed entropy, and the result of a collision would be disastrous and also impossible to debug.

Our goal was to minimize the odds of collision by introducing a constantly increasing factor (i.e., time), such that the odds plummet if the symbol generator is not called in the same millisecond. On reflection, though, perhaps we meant to sum the two—multiplying current millis by the result of `Math.random()` reduces the odds of collision but it doesn't do much to provide stronger guarantees around avoiding collisions if the result of `Date.now()` changes.

Comment (ef4) [inline packages/ember-metal/lib/utils.js]: I think you're actually increasing the odds of collision significantly, not reducing them.

"Not cryptographically strong" just means that it's possible to make better-than-expected guesses about future values based on past values. It doesn't mean the distribution is skewed. `Math.random()` is supposed to give a reasonably uniform distribution over 64 bits.

When you multiply by date and cast down to integer, you throw away roughly 24 bits worth of entropy, because the date is only going to be roughly `2^40`. So you end up with only the integers integers from 0 to 2^40.

If instead you did roughly:

    var MAX_DOUBLE = Math.pow(2, 64);
    return Math.floor(Math.random() * MAX_DOUBLE);

you will get integers from 0 to 2^64.

File: packages/ember-htmlbars/lib/env.js [hunk 3]
```diff
@@ -2,35 +2,70 @@ import environment from "ember-metal/environment";
...
 
+import debuggerKeyword from "ember-htmlbars/keywords/debugger";
+import withKeyword from "ember-htmlbars/keywords/with";
+import outlet from "ember-htmlbars/keywords/outlet";
+import unbound from "ember-htmlbars/keywords/unbound";
+import view from "ember-htmlbars/keywords/view";
+import componentKeyword from "ember-htmlbars/keywords/component";
+import partial from "ember-htmlbars/keywords/partial";
+
+merge(emberHooks.keywords, {
```
Comment (chadhietala) [inline packages/ember-htmlbars/lib/env.js]: Currently there are no upstream keywords in HTMLBars, so I believe this needs to be:
```
emberHooks.keywords = {};
merge(emberHooks.keywords, {...});
````

**Comment by rwjblue** [comment]
Updated title + description based on EmberConf presentation.

**Comment by toblender** [comment]
Minor correction: teack === track?

**Comment by morenoh149** [comment]
@toblender yeah. I thought he meant `teach`

**Comment by darkbaby123** [comment]
@wycats You mentioned a lot about diffing values to check if they're dirty. I'm curious what's the difference between Glimmer's diffing logic and Angular's dirty-checking.

As I know Angular dirty-checking also checks values (expressions) one by one and execute corresponding callbacks (mostly change doms). But:
1. Angular doesn't have run loop so it's can not batch update doms.
2. watchers need to be triggered by `$apply()` manually sometimes.

**Comment by drogus** [comment]
> I'm curious what's the difference between Glimmer's diffing logic and Angular's dirty-checking.

These two diffing situations are not happening at the same level. Angular's diffing happens outside of a view layer in order to check if a template change is needed. So let's say that you have a `user = { login: 'drogus' }` object. And you use it in a template as `<span class="login">{{user.login}}</span>`. Now, in order to update the template automatically you need to know if a value of the `user` object changed. In Angular it's done by dirty checking all of the properties used in templates. In Ember properties are observed, so it knows when a property is changed.

This PR and diffing described here happen in a view layer when a framework already knows that it needs to rerender something, but it needs to figure out what to rerender exactly. DOM is slow, so regenerating the entire template may be costly and here comes the diffing algorithm that React started with.

File: packages/ember-metal/lib/utils.js (hunk 2 above)
Comment (jdalton) [inline packages/ember-metal/lib/utils.js]: Ran this in IE11 overnight and no collisions.

**Comment by bitinn** [comment]
One interesting side-effects of React (or other similar dom-diffing) approach is you can worry less about what's being updated in DOM (as oppose to update them manually on value change).

What sort of limit will value-diffing approach impose on DOM manipulation? Would you say this approach is closer to something like [Riot](https://muut.com/riotjs/compare.html#string-based-vs-dom-based) than React?

File: packages/ember-metal/lib/utils.js (hunk 2 above)
Comment (loopmode) [inline packages/ember-metal/lib/utils.js]: I came from using millis to multiplying by random in that particular order, so the idea was to allow for more possible values during a single CPU cycle. Maybe the author had a similar purpose in mind.

**Comment by mixonic** [comment]
@bitinn your understanding is pretty good. I think the comparison to Riot is a good one.

Your points one and two are correct IMO. Point three is a bit off, but I'm not sure what you are thinking when you say "traditional template renderer". A full rerender in glimmer will re-use the static DOM anywhere the template being used has not changed, and will only update dynamic content if it has changed. Where the template has changed, Glimmer will `cloneNode` a cached fragment of pre-hydrated DOM.

I'm sure the architecture will be discussed in more details as this gets closer to landing.

**Comment by jonathanKingston** [comment]
Is the intention to swap out `ShadowRoot` with `document.ShadowRoot` eventually?

**Comment by raytiley** [comment]
Just built latest code from this branch and `core_view` is throwing tons of `utils.typeOf is not a function`. Is this the best way to report issues when trying out this branch?

```js
 has: function (name) {
      return utils.typeOf(this[name]) === "function" || this._super(name);
    }
```

**Comment by rwjblue** [comment]
@raytiley - Thanks for reporting, was introduced in #10990 and fixed in a2d9a41.

**Comment by raytiley** [comment]
I still don't think `actions` are being dispatched correctly. I have the following template for a `schedule` route.

```htmlbars
{{#schedule-drag-canvas class="clearfix"}}
	<div class="schedule-main">
		{{outlet}}
	</div>

	{{#right-side-drawer class="schedule-side-pane"}}
		{{outlet 'schedule-sidebar'}}
	{{/right-side-drawer}}

	{{schedule-drag-helper}}
{{/schedule-drag-canvas}}
```

Actions happening inside the default `{{outlet}}` are raising an error that the `schedule-drag-canvas` component does not handle the action. That action should not be going to the`schedule-drag-canvas` it should be going to `ScheduleController` and then bubbling up the route hierarchy where I handle it in `ScheduleRoute`.

**Comment by chadhietala** [comment]
It appears file size gzipped is about 9kb larger then the 1.11.2 and 8kb from 1.12.0-beta.  Not sure if this is to be expected.

**Comment by rwjblue** [comment]
@chadhietala - Canary builds are always larger than stable/beta builds due to the feature flag process (all flagged code is still included in canary builds but is completely stripped from beta/stable).  Just how much the difference is after that I am unsure...

**Comment by chadhietala** [comment]
@rwjblue Ah yes, forgot about defeatureify. I should know this by now.

**Comment by ef4** [comment]
I also wouldn't get too excited about the size falling until 2.0. Glimmer is fully backward compatible still. It's at 2.0 that we get to drop cruft.

**Comment by blesh** [comment]
FYI: I was speaking with @stefanpenner last night about some perf issues we had, and I put together this example: https://github.com/blesh/is-ember-really-fast-yet

Just pull it down and run it

I didn't include a baseline, but we have one here, it's complicated because it's all D3 but it runs in about 1 sec (as opposed to ~16secs)

I hope this is helpful.

**Comment by wycats** [comment]
@blesh 1s instead of 16s sounds better? Or did I misunderstand?

**Comment by blesh** [comment]
@wycats ... I was saying it currently takes 16 seconds to render 60 graphs with an {{#each}}... @stefanpenner helped me find that 10 seconds of that was the graph component. But the remaining 6 is still pretty fair away from the baseline of ~1 second if things are done in pure d3.

**Comment by blesh** [comment]
@wycats, after updates and testing, it was a negligible amount that was actually ember-nf-graph. There were perf issues, for sure, but fixing them didn't make a huge difference.

**Comment by bcardarella** [comment]
ZOMG

**Comment by raytiley** [comment]
Getting an error pretty regularly about `morph.clear()` is not a function. Not sure if its related the todo in the code. I'm not exactly sure how you get a logical child that's not in the dom.

windows 7 x64 2015-05-04 10-00-26

**Comment by rwjblue** [comment]
We have 3 tests still skipped at the moment (the fixes are in various stages of in-flight). I recommend that we merge, and iterate on the remaining issues in canary.  To make this a nice stable beta (in roughly a week) we need more users to be able to test these changes in their applications and report any issues they come across.

@emberjs/owners - Any objections?

**Comment by wycats** [comment]
@rwjblue works for me. I plan to have a blog post explaining the status and remaining open issues in the morning (Greek time).

**Comment by chadhietala** [comment]
:shipit: Will hook it up to an app this week.

**Comment by blesh** [comment]
So I ran `1.12.0-beta.1+canary.27ed45f8` against https://github.com/blesh/is-ember-really-fast-yet

Unfortunately, I didn't see much improvement for my use case of graphs in an each. Most of the time spent is in `scheduleRender`, which is a little hard to see in the production build profile. 

Here's what the production build profile looks like:

screen shot 2015-05-04 at 4 25 14 pm


It takes about 8-9 seconds to render, as opposed to a baseline of ~1sec. (You can see the baseline if you clone the repo and run it, navigating to http://localhost:4200/basline, thanks to @jeff3dx)

Graphs in an each weren't the only place I've seen this particular issue. Basically any large number of views or components in an each will cause this slowness.

I have the .cpuprofile file if you're all interested.

cc/ @stefanpenner

**Comment by rwjblue** [comment]
@blesh:

This refactor addresses re-render performance by avoiding creating, destroying, and re-recreating DOM elements and views/components. It does improve the cost of view/component instantiation, but not significantly (which I would suspect is a fairly significant factor in the case you reference).  There are a number of contributing factors to the initial view render (as a few others have mentioned), and this PR is definitely a step in the right direction.

This refactor along with some Ember 2.0 spring cleaning and straight up performance work, will address the initial render time speed issues your examples are referencing.

**Comment by sandstrom** [comment]
@blesh I feel this pain too, but I think it's orthogonal to glimmer. [This dedicated issue](https://github.com/emberjs/ember.js/issues/10261) is better to track the case you mention.

I've created a test-repo without the graph component (easier to investigate performance without third-party code), running on Glimmer (even though I don't think that has much of an effect, for the reasons @rwjblue mentions).

**Comment by Emerson** [comment]
Congrats on the merge - been following along since Ember Conf - super exciting stuff!

**Comment by listrophy** [comment]
clapping

**Comment by rtablada** [comment]
There was much rejoicing

**Comment by danmcclain** [comment]
tumblr_m3vi749jwv1r3zat8

**Comment by jdjkelly** [comment]
005385766_2cool

**Comment by thejameskyle** [comment]
*googles "glimmer gif"* [](http://media.tumblr.com/b2224c4ba1a26dff4663e61249fcdb4d/tumblr_inline_mhy9grcKMM1ropvqs.gif)

**Comment by rtablada** [comment]
@thejameskyle results may vary

**Comment by jdalton** [comment]
woooooooo!

**Comment by MattMSumner** [comment]
i_love_it

**Comment by jeanleonino** [comment]
Amen!

**Comment by bartocc** [comment]
Congrats !

**Comment by Adriaaaaan** [comment]
Anyone got it working yet?  I just get 
> Uncaught TypeError: Cannot read property 'forEach' of undefined

childviews doesn't exist

```javascript
    appendChildren: function(view, children, retained) {
        var self = this;
        var childViews = view.get('_childViews');

        childViews.forEach(function(childView) {
          if (!(childView instanceof Ember.Object)) { return; }

          if (self.shouldShowView(childView)) {
            var grandChildren = [];
            children.push({ value: self.inspectView(childView, retained), children: grandChildren });
            self.appendChildren(childView, grandChildren, retained);
          } else {
            self.appendChildren(childView, children, retained);
          }
        });
      },
```

**Comment by mixonic** [comment]
@Adriaaaaan `_childViews` is a private API that has been removed. Please use `view.get('childViews')`.

**Comment by WillsonSmith** [comment]
eznaclq

**Comment by bdvholmes** [comment]
Woohoo!

**Comment by oskarrough** [comment]
Just updated from 1.11.1 and it took five minutes to get everything working through all your console.logs. So good!

**Comment by Fed03** [comment]
image

**Comment by tubbo** [comment]
http://i.imgur.com/epVWJFE.gif

**Comment by btecu** [comment]
Great work!

**Comment by Adriaaaaan** [comment]
Great work! although our app is currently very broken still I'm already seeing a huge improvement in performance in my list views.  Now i just have a million deprecation warnings to fix

**Comment by wycats** [comment]
@Adriaaaaan That's great news! Please do report any notable breakage. We want things to be pretty clean by the time we ship 1.13 final :)

You might also want to run in prod mode to check out perf. Those deprecation warnings aren't free to generate ;)

**Comment by chrism** [comment]
Great Work!

Anyone using Liquid Fire should check that https://github.com/ef4/liquid-fire/issues/276 has been resolved before updating as it is not yet glimmer compatible.

**Comment by jmurphyau** [comment]
@wycats any help you can provide on unbound helpers? A helper that produces a stream like value that can be invalidated causing the value in the template to update? Trying to get [ember-get-helper](https://www.npmjs.com/package/ember-get-helper) to work with glimmer.. Simply returning a new child stream (e..g `objectStream.get(key)`) doesn't cause a new value to render in the template when that value changes.. Do I need to look into some of the hooks or somehow subscribe <some object> to the new stream?

**Comment by jmurphyau** [comment]
I can't seem to find that really detailed description of all the HTMLBars lifecycle hooks etc.. Do you have a link to that that you could provide?

**Comment by wycats** [comment]
@jmurphyau right now there is no public way for a helper to express dynamic dependencies, but that's a good idea. 

Glimmer intentionally doesn't expose the internal stream machinery; it's changing quite a bit still, but it makes sense for a helper to be able to tell Ember when to invalidate it. 

It also kind of makes sense for us to include this get helper in Ember itself honestly. It's a primitive, like `{{component}}`.

**Comment by wycats** [comment]
@jmurphyau as I said in the blog post, more info on the life cycle hooks is forthcoming :)

**Comment by Adriaaaaan** [comment]
@wycats Hmmm have looked into it more, I'm now seeing a rather significant performance regression.  related to interacting with sub resources templates from a list.  It seems that interacting with it causes the the whole tree to redraw making it unusable if there are a lot of rows per page.  1.11 is faster, its most notable when selecting the rows (the detail page is very laggy at appearing, the more rows in the list the longer it takes).  Although it is clearly much faster at rendering (the page appears much faster) interacting with it is much worse as it seems to be doing more work everytime something changes.  I'll see If I can make a simple jsbin

**Comment by jiyinyiyong** [comment]
Hi, you mentioned there's slide in EmberConf 2015. But is there a video?
I can't find it in the list "EmberConf 2015 by Confreaks"
https://www.youtube.com/playlist?list=PLE7tQUdRKcyacwiUPs0CjPYt6tJub4xXU

**Comment by igorT** [comment]
@jiyinyiyong it's the keynote, towards the end

**Comment by jiyinyiyong** [comment]
@igorT I don't get it. Could you point it out in the video?

**Comment by blessenm** [comment]
Stupid question. So there is no virtual DOM in ember right? Just value diffing to find which part of the DOM needs to be manipulated.

**Comment by axemclion** [comment]
Glimmer is pretty fast - almost 25% faster !! Ran some tests and results here - http://blog.nparashuram.com/2015/05/performance-boost-in-emberjs-from.html

**Comment by jdurand** [comment]
@blessenm instead of diffing DOM it diffs a tree of possibly mutable states that are bound to the real DOM. It doesn't need to maintain a virtual DOM because it has deeper knowledge of your apps state.

**Comment by blessenm** [comment]
@jdurand thanks for the clarification.

**Comment by ballPointPenguin** [comment]
The Glimmer Twins

**Comment by jmurphyau** [comment]
@wycats someone has asked a relatively simple question on [stackoverflow](http://stackoverflow.com/questions/30776252/streams-in-ember-js) and in [slack](https://embercommunity.slack.com/archives/random/p1434100649001108) - 'what is a stream'.. A answered as best I could but wanted to bring it up here - since this is where he got it from - what is a stream?

**Comment by matthewp** [comment]
Is there somewhere that explains how Glimmer works in more detail, with links to code maybe? Given how many commits are included in this PR it's hard to figure out how the details are implemented in practice.  For example you say:

> On initial render, we track the last value (always a primitive) that we inserted into the DOM.

But I can't find in the code where this happens. And I don't know what you mean by a primitive value.  I assume you mean that you track attribute string values and text node's string nodeValues but am having a difficult time finding where this happens in the code.

Is there maybe one or two commits that contain most of the work that I can look at?

**Comment by ef4** [comment]
@matthewp Much of the infrastructure is actually in https://github.com/tildeio/htmlbars

There's not really a single commit to point to -- the work was extensive and many people put in hundreds of commits.
