### ISSUE TITLE
Uncaught TypeError: object is not a function

### ISSUE THREAD

**Issue by ninja-** [emberjs/ember.js#10693]
```js
      outerContextualElement: function() {
        if (!this._outerContextualElement) {
          Ember.deprecate("The render buffer expects an outer contextualElement to exist." +
                          " This ensures DOM that requires context is correctly generated (tr, SVG tags)." +
                          " Defaulting to document.body, but this will be removed in the future");
          this.outerContextualElement = document.body;
        }
        return this._outerContextualElement;
      },

      innerContextualElement: function(html) {
        var innerContextualElement;
        if (this._element && this._element.nodeType === 1) {
          innerContextualElement = this._element;
        } else {
          innerContextualElement = this.outerContextualElement(); <- here
        }
```

This error is hard to debug, it happens during transitions. I'll try to gather more details soon.

**Comment by ninja-** [comment]
Actually...this seems fixed after updating to latest git version from 1.10
