### ISSUE TITLE
Using `ObjectProxy.prototype` as a mixin throws MANDATORY_SETTER

### ISSUE THREAD

**Issue by sumeetattree** [emberjs/ember.js#18050]
Digging through other issues, it looks like related issues have been brought up in the past, but the way I am using it is slightly different. Here https://github.com/emberjs/ember.js/issues/3403

After recently upgrading to 3.10 (This problem exists in 3.9 as well. This worked fine on 3.8). I have started facing this error:
```js
Error: Assertion Failed: You must use set() to set the 
`content` property (of <game-client@service:current-player::ember528>)
to `<game-client@model:player::ember529:129>`
```

which is coming from line 131:
https://github.com/emberjs/ember.js/blob/91656e1154afe39791514cbe937ada954eab8d11/packages/%40ember/-internals/metal/lib/property_set.ts#L129-L137
precisely `meta.peekWatching(keyName)` is `0`

The use case is that if the `current-player` service does not implement a method or a property, the lookup should happen on the underlying `content` property that is an instance of the `player` model.
I was using `ObjectProxy.prototype` as a mixin since I couldn't find any other way to convert a Service into a proxy itself. Here is the sample code.

```js
// lib/shared/services/channel.js <-- a 'shared' in repo addon'
export default Service.extend(Evented, ObjectProxy.prototype, {
  // set the content property later somewhere after init
});

// this service is then extended again in current-player.js
// lib/<in-repo-engine>/services/current-player.js
export default Channel.extend({
  someTask: task(function* someTask() {
    this.set('content', model); // <-- Fails
  })
});
```

Not sure what has caused this to start failing now. Is this not the recommended way to use the `ObjectProxy`? Since the object proxy mixin is not public, I figured this should work. Is there any alternative that preserves the current use case?

**Comment by locks** [comment]
Closing as stale. The framework has been moving away from `EmberObject`, so it is unlikely changes will be make to that part of the system. Thanks for reporting!
