### PR TITLE
[CLEANUP beta] Update GlimmerVM to 0.81

### PR DESCRIPTION
**Pull request by rwjblue**
High level breaking changes:

* removes deprecation of mutations during helper compute
* removes deprecation of mutations during unknownProperty
* `@glimmer/integration-tests`, `@glimmer/manager`, `@glimmer/validator`
  * [#1330](https://github.com/glimmerjs/glimmer-vm/pull/1330) Remove deprecated support for mutation after consumption during certain manager hooks ([@snewcomer](https://github.com/snewcomer))
* `@glimmer/manager`
  * [#1328](https://github.com/glimmerjs/glimmer-vm/pull/1328) Remove deprecated Component Manager version 3.4 ([@nlfurniss](https://github.com/nlfurniss))
* `@glimmer/integration-tests`, `@glimmer/manager`
  * [#1329](https://github.com/glimmerjs/glimmer-vm/pull/1329) Remove deprecated Modifier Manager version 3.13 ([@nlfurniss](https://github.com/nlfurniss))

See full details here:

https://github.com/glimmerjs/glimmer-vm/releases/tag/v0.81.0

Closes #19735
Closes #19731

### CODE REVIEW

**Comment by snewcomer** [comment]
@rwjblue Does this PR need to be cherry-picked or copied into here?

https://github.com/emberjs/ember.js/pull/19735

**Comment by nlfurniss** [comment]
I think you'll need to cherry-pick #19731 to fix some failures

**Comment by rwjblue** [comment]
Thanks @snewcomer / @nlfurniss - I've merged both of those PR's into this branch.

**Comment by nlfurniss** [comment]
Looking into the failures and here is at least one fix:

[https://github.com/glimmerjs/glimmer-vm/pull/1343](https://github.com/glimmerjs/glimmer-vm/pull/1343)

**Comment by nlfurniss** [comment]
And this diff fixes the rest of the tests (and I believe it's correct)

```diff
diff --git a/packages/@ember/-internals/glimmer/tests/integration/components/angle-bracket-invocation-test.js b/packages/@ember/-internals/glimmer/tests/integration/components/angle-bracket-invocation-test.js
index 34a696ab5..1bb86b5c4 100644
--- a/packages/@ember/-internals/glimmer/tests/integration/components/angle-bracket-invocation-test.js
+++ b/packages/@ember/-internals/glimmer/tests/integration/components/angle-bracket-invocation-test.js
@@ -9,7 +9,7 @@ import { Component } from '../../utils/helpers';
 
 class CustomModifierManager {
   constructor(owner) {
-    this.capabilities = modifierCapabilities('3.13');
+    this.capabilities = modifierCapabilities('3.22');
     this.owner = owner;
   }
 
diff --git a/packages/@ember/-internals/glimmer/tests/integration/custom-component-manager-test.js b/packages/@ember/-internals/glimmer/tests/integration/custom-component-manager-test.js
index c4d6552f3..62e9b576a 100644
--- a/packages/@ember/-internals/glimmer/tests/integration/custom-component-manager-test.js
+++ b/packages/@ember/-internals/glimmer/tests/integration/custom-component-manager-test.js
@@ -463,6 +463,7 @@ moduleFor(
           return EmberObject.create({
             capabilities: componentCapabilities('3.13', {
               asyncLifecycleCallbacks: true,
+              updateHook: true,
             }),
 
             createComponent(factory, args) {
@@ -668,6 +669,7 @@ moduleFor(
         capabilities: componentCapabilities('3.13', {
           destructor: true,
           asyncLifecycleCallbacks: true,
+          updateHook: true,
         }),
 
         createComponent(factory, args) {
```

**Comment by nlfurniss** [comment]
looks like only `@test it does not resolve helpers with a `.` (period)'` is failing

**Comment by snewcomer** [comment]
Yep I was debugging that on the glimmer side.  There are some op codes that I was tracking down in glimmer.  Perhaps will make some progress but if you happen to know, would love to chat about it.

**Comment by rwjblue** [comment]
@ef4 is looking into the failing test here, to figure out what is going on. It is totally plausible that the test just isn't valid any longer, but it does seem strange that we don't get a better assertion / failure message.

**Comment by ef4** [comment]
After investigating I think the test failure is revealing a legitimate bug in glimmer-vm. The `GetFreeAsFallback` opcode is broken.

Here's a PR to try and remove it entirely instead: https://github.com/glimmerjs/glimmer-vm/pull/1362

**Comment by ef4** [comment]
With the above glimmer-vm PR, there's still an exception in that test, but now it's a proper error and not a VM crash:

> Error: Attempted to resolve a value in a strict mode template, but that value was not in scope: hello

I think the behavior is now correct, although the wording of the error message is misleading. When it was written, it could probably only be reached in strict mode. But now that the `this` fallback is removed it can be reached in certain positions even in loose mode. In this case, given that `hello` is a free variable, this:

```hbs
{{hello.world}}
```

supports only strict resolution, since there's nowhere else it can come from, because  we never supported globals resolution of this syntax.

**Comment by rwjblue** [comment]
Note: I'm working on rebasing now that glimmer-vm 0.83.1 is released

**Comment by rwjblue** [comment]
CI will fail until https://github.com/emberjs/ember.js/pull/19830 lands
