### ISSUE TITLE
Regression - appendChild no longer accepts a class

### ISSUE THREAD

**Issue by raycohen** [emberjs/ember.js#11163]
Seen when upgrading from 1.11.1 to 1.13-beta.1, and verified the same behavior on ember master.

We had (admittedly old) code doing the following:
```js
Ember.View.extend
  render(buffer):
    ...
    this.appendChild(aViewClass)
    ...
```

This now errors with "instance.trigger is not a function" [here](https://github.com/emberjs/ember.js/blob/e753dfc81637c5f14cac606e3f49d12190d77a70/packages/ember-views/lib/mixins/view_child_views_support.js#L124)

In our usage, the `instance` variable is `aViewClass` above - ie. not a view **instance** but rather a view **class**.

**Comment by mixonic** [comment]
@raycohen we greatly simplified the `render()` implementation, and really all you get now is an array (with `push`). This may be too simple, and we will keep an eye on the feedback coming in. Before making the change, we scoured the web for anyone using `appendChild` in `render()` and didn't find anything.

The ability to append a child view during `render` has been removed. That API was tied to how Handlebars templates rendered, and would be difficult to implement for a fairly very number of old codebases.

So let's keep this open and get more feedback, but unless you guys have a very compelling use-case we're not likely to invest more time in getting `render()` to behave exactly as it did with Handlebars.

**Comment by acorncom** [comment]
Given the lack of feedback here in the last year from other folks, I'll go ahead and close this issue.  If we need to re-open it, let me know!

**Comment by dlo83** [comment]
@acorncom This issue leaves us dead in the water in terms of upgrading our app from 1.12 to 1.13, as one of the cornerstones of our application is a View that creates dynamic components with attributes bound correctly.  We have a parallel effort to upgrade our application the correct way and create components using a combination of ```{{#each foo as |bar|}}```, the component helper, etc., but given that we're using 90+ components, it's been a slog.  We'd really like to get on 1.13 ASAP to install some addons that rely on it, but this is a blocker for us.

Our current implementation is as follows:

```
render: function(buffer) {
    var parts = get(this, 'dataToRender');
    if (!parts || parts.length === 0) { return; }

    for (var i = 0, l = parts.length; i < l; i++) {
      var currentPart = parts[i];

    if (typeof currentPart === 'string') {
        buffer.push(currentPart); // Just DOM
      } else {
        // grab the appropriate component and attach the bindings found in data to the component
        var Component = this.getComponentForName(currentPart.componentName);
        this.appendChild(Component, currentPart);
      }
    }
  },
```

Can you think of any way we can accomplish the same functionality now that the render() function has been refactored in 1.13?

Any help would be much appreciated.  Cheers.

**Comment by acorncom** [comment]
@dlo83 ouch, that sounds painful :-/ I'm not that familiar with the older Views approach, so not much help on the code front.  At this point, the core team has shifted priorities to the Ember 2.x, so I doubt we'd be able to do much as far as changing code.

Unless @mixonic has some ideas, I think your best bet might be to ask your question on the Ember Community Slack (either `#-help` or `#general`) to get some advice from folks who have more experience with this stuff.
