### ISSUE TITLE
Set is not working in Ember 2.6.2

### ISSUE THREAD

**Issue by hamzahio** [emberjs/ember.js#14387]
good day i create new project and create this

Controller
```
import Ember from 'ember';

export default Ember.Controller.extend({
  data:[],
  actions: {
    create(){
      this.get('data').pushObject({'name':'jon'})
    },
    change(name,preson){
      preson.set('name',name)
    }
  }
});
```

Templates
```
<button {{action 'create'}}>create</button>
{{#each data as |person|}}
  <div class="">
    {{person.name}}
    {{input value=newName type="text"}}
    <button {{action 'change' newName person}}>change</button>
  </div>
{{/each}}

```

when i click change button i got this error 
```
preson.set is not a function
```

**Comment by trek** [comment]
Could you create an [Ember Twiddle](https://ember-twiddle.com/) duplicating this issue. Without being able to see the objects in `data` being used in `{{#each data as |person|}}` I can't tell but if I had to guess I would say the value of `preson` is either accidentally `undefined` (and will have no `set` function) _or_ is not instance of `Ember.Object` (which means it will also not have `set` and you'd need to use the "functional" style for setting: `set(preson, 'name', name`)`

Thanks!

**Comment by hamzahio** [comment]
the project is new and only ember new

**Comment by hamzahio** [comment]
https://ember-twiddle.com/54a9045a0427e0a9df0db1ab259ef2b2?openFiles=controllers.application.js%2C

**Comment by trek** [comment]
Indeed: the objects inside `data` (from your call you `pushObject({'name':'jon'})`, not instances of `Ember.Object`.

You can either make them `Ember.Object` instances with `pushObject(Ember.Object.create({'name':'jon'}))` when adding them to the collection or use the "functional" style of set if you prefer to use POJO (Plain Old JavaScript Objects) for the data:

```
    change(name,preson){
     set(preson, 'name',name)
    }
```
