### ISSUE TITLE
Emberjs 1.8 causes testing case wrong.

### ISSUE THREAD

**Issue by weichienhung** [emberjs/ember.js#5524]
Hi 

I have a lobby index route.
```
application.LobbyIndexRoute = Ember.Route.extend({
    redirect: function() {
      this.replaceWith('lobby.dashboard');
    }
});
```

A test case.
```
test("should redirect to dashboard", function() {
    Ember.run(this,function(){
      route = App.__container__.lookup('route:lobby.index');

      sinon.spy(route, "replaceWith");
      route.redirect();
      ok(route.replaceWith.calledOnce, "replaceWith should be calledOnce");  
    });
});
```
The test case works fine in emberjs 1.5 but after i upgraded to emberjs 1.8. it fails.
Fail reason:
TypeError: 'undefined' is not a function (evaluating 'getHandler(name)')

BTW, i try the emberjs 1.6.1 and the test case pass. emberjs 1.7 and 1.8 fail.

**Comment by rwjblue** [comment]
The issue was that around 1.8 we deferred setting up the router until after the first call to `visit`.

Demo with current release branch: http://jsbin.com/podolu/edit?html,js
