### ISSUE TITLE
{{render 'navigation'}} won't render navigation.hbs if navigation view is present

### ISSUE THREAD

**Issue by Kuzirashi** [emberjs/ember.js#10760]
In Ember 1.12-beta1 `{{render 'navigation'}}` won't render `navigation.hbs` if `navigation` view is present. If I rename `navigation` view to something else template is being rendered. However I need both `view` and `template`. I have more render template + view situations in my app. Is this regression or wanted effect?

When views/navigation is present it uses only this file, doesn't care about template(nav tagName is specified in `navigation.coffee`):
![zrzut ekranu z 2015-03-29 15 03 14](https://cloud.githubusercontent.com/assets/4950658/6885541/d7e4c2c2-d624-11e4-80de-2c4e71b15395.png)

When there is no view with navigation name(only template rendered):
![zrzut ekranu z 2015-03-29 15 02 35](https://cloud.githubusercontent.com/assets/4950658/6885547/f75fee42-d624-11e4-87b6-0e13e1fe50ea.png)

In Ember.js 1.11-beta5 it works as expected(view combined with template):
![zrzut ekranu z 2015-03-29 15 06 20](https://cloud.githubusercontent.com/assets/4950658/6885551/3676bdb8-d625-11e4-8e54-2184dd10ab72.png)

In Ember 1.12-beta1 I have to specify `templateName: 'navigation'` in my `view/navigation` to make it work as expected.

**Comment by mixonic** [comment]
@Kuzirashi sounds like a regression. A simple reproduction with emberjs.jsbin.com would be helpful, thanks.

**Comment by Kuzirashi** [comment]
Ok so it's actually present in 1.11 stable not in 1.12(I mean it's earlier in 1.11, not 1.12 fault).

Ember 1.10 working fine:
http://emberjs.jsbin.com/tasutuduqo/2/

Ember 1.11 bad:
http://emberjs.jsbin.com/tasutuduqo/3

**Comment by hemp** [comment]
I think hit the same thing when moving to 1.11.0 stable from 1.11.0-beta.5 when leveraging the {{render ".."}} helper (we'll have to switch it to a component soon enough).

Chrome Canary has a better error:   `TypeError: pointer._parentOutlet is not a function`

`ember.debug.js:18946:  while (pointer && (po = pointer._parentOutlet())) {`

**Comment by Kuzirashi** [comment]
Demos to recreate my and @hemp issue:

Nested `{{render}}` working in Ember 1.10:
http://jsbin.com/beceverobe/3

Nested `{{render}}` not working in Ember 1.11:
http://jsbin.com/beceverobe/2

**Comment by MichaelVdheeren** [comment]
+1, having same problems

**Comment by manufaktor** [comment]
I'm having the same problem. I can work around it by explicitly setting the templateName in the view.

**Comment by EmergentBehavior** [comment]
Also running into this issue in 1.11 but, like @manufaktor, I'm finding if you explicitly specify `controller` and `templateName` etc. (as appropriate) I no longer have issues.

**Comment by Kerrick** [comment]
I've also been bitten by this bug in the upgrade to Ember 1.11 from Ember 1.10.

**Comment by awaer** [comment]
Confirmed here. Broken in 1.11 (unless templateName is explicitly defined on view); works in 1.11.0-beta.5.

**Comment by davidpett** [comment]
having this issue too

**Comment by rwjblue** [comment]
Looks related to https://github.com/emberjs/ember.js/issues/10710#issuecomment-85294290 (which was addressed in https://github.com/emberjs/ember.js/pull/10712).

**Comment by davidpett** [comment]
thanks @rwjblue! so the expected behavior is to always define the `templateName` in the View? This is a change from past behavior where it would automatically grab the template based on the name of the view.

**Comment by rwjblue** [comment]
@davidpett - Yes, I am now questioning the change made in #10712. This seems to be a regression, though it does solve the issue from #10710.

I will try to dig into this tonight/tomorrow morning, and try to fix both the issue in #10710 and not break this use case.

**Comment by awaer** [comment]
@rwjblue I'm also seeing some errors in `impersonateAnOutlet` even after I've defined `templateName` on the view, where `pointer._parentOutlet` is not a defined function.

**Comment by davidpett** [comment]
thanks @rwjblue

**Comment by awaer** [comment]
Here is an example of the error described in my previous comment: http://emberjs.jsbin.com/feyakinure/1/edit?html,js,output

**Comment by Adriaaaaan** [comment]
my app is totally broken by this but I've already started using the new {{component}} helper (which is awesome btw).   Any chance of a patch release?

**Comment by Adriaaaaan** [comment]
as far as I can tell it just breaks because its trying to find the top level "outlet" but doesn't stop when it finds it?
adding an undefined check seems to fix it for me

in    function impersonateAnOutlet(currentView, view, name) 
```javascript
    while (pointer && pointer._parentOutlet!=undefined && (po = pointer._parentOutlet())) {
```

**Comment by trek** [comment]
@Adriaaaaan the bug fix should appear in the next point release after a fix lands on master :train: :train: :train: Until then, please use the previous release you were using.

**Comment by marcemira** [comment]
Same problem here

**Comment by tonywok** [comment]
Anyone have a workaround for apps using a pod structure?

**Comment by rwjblue** [comment]
Sorry for the delay here https://github.com/emberjs/ember.js/pull/10822 should fix this.

**Comment by trek** [comment]
Closing in favor of #10822. Let us know if that doesn't resolve the issue for you.

**Comment by manufaktor** [comment]
Thanks! :+1:

**Comment by awaer** [comment]
@rwjblue I'm still seeing a `TypeError: undefined is not a function` error with a nested `{{render}}` -- was this addressed as a part of the fix here? It seems that the problem described above where `pointer._parentOutlet()` is undefined is still happening with 1.11.1. You can see the error triggered in [this example](http://emberjs.jsbin.com/moxugi/1/edit?html,js,console,output).

**Comment by rwjblue** [comment]
@awaer - Please open another issue to track this (definitely seems like a regression upon initial perusal of the JSBin you provided).
