### ISSUE TITLE
window.require is not a function

### ISSUE THREAD

**Issue by cjdxhjj** [emberjs/ember.js#21003]
### 🐞 Describe the Bug
the production build asserts can't run on browser

### 🔬 Minimal Reproduction
Describe steps to reproduce. If possible, please, share a link with a minimal reproduction.

<img width="1122" height="503" alt="Image" src="https://github.com/user-attachments/assets/d7d64c14-cfff-4779-a946-fb4594f3ef54" />

### 😕 Actual Behavior
A clear and concise description of what is happening.

<img width="666" height="155" alt="Image" src="https://github.com/user-attachments/assets/b0283686-9f27-4b6c-bc42-fef64506bc25" />

<img width="483" height="616" alt="Image" src="https://github.com/user-attachments/assets/24d83947-e755-4a3d-92ed-9e2a09df3323" />

<img width="965" height="516" alt="Image" src="https://github.com/user-attachments/assets/563a6252-ae5a-4912-97a1-d5856d19d90f" />

I tried commenting out the deprecation-workflow, but it still appears in the output.

### 🤔 Expected Behavior

The default build output file main is too large. Additionally, its naming differs significantly from previous versions—there is no project name included, only generic prefixes like main and modules. Moreover, assets such as CSS files and images are not compressed with hash values appended.

### 🌍 Environment

- Ember: - 6.8.1
- Ember-CLI: - 6.8
- Node.js/npm: - 25.1.0
- OS: - windows 10
- Browser: - edge 142

**Comment by cjdxhjj** [comment]
<img width="1050" height="119" alt="Image" src="https://github.com/user-attachments/assets/c757ba60-e68d-47b8-9041-937cb5facfc6" />
When I replaced window.require('./package').name with "xxx", it still throws the error "Ww is not a function".

**Comment by cjdxhjj** [comment]
<img width="614" height="632" alt="Image" src="https://github.com/user-attachments/assets/361e9552-84f8-4389-a317-199864c88b99" />

**Comment by cjdxhjj** [comment]
<img width="907" height="707" alt="Image" src="https://github.com/user-attachments/assets/8aaa8c64-7932-45a9-bc99-1e93c718b27d" />

<img width="1057" height="434" alt="Image" src="https://github.com/user-attachments/assets/4a407586-7c3b-43e8-bce7-2b4d2a47138a" />

**Comment by lifeart** [comment]
HI @cjdxhjj, thank you for report!
Try to install https://github.com/ef4/ember-auto-import/

If it not help, do you mind to create and share minimal reproduction repo to be able to poke on it?

**Comment by cjdxhjj** [comment]
@lifeart thanks for your replay
I've tested multiple times, and the issue likely stems from problems during dependency installation. My project uses Ember 6.8, which includes the ember-auto-import component by default. The problem occurred when I upgraded an old Ember 6.6 project to 6.8.
First, I created a new project using Ember CLI. Then, I used Beyond Compare to compare and merge the configuration files from the new project, adopting nearly all Ember 6.8 configurations except for a few additional installed packages. After that, I deleted the node_modules folder and ran npm install—this is when the aforementioned issue appeared.
Next, I tried running npm install on the new project, but encountered the same problem. However, when I created another new project and tested it, it worked unexpectedly. I then deleted the node_modules of the previously created new project and tested again—it also worked.
The old project, though, still failed after several attempts. So I backed up the old project, deleted it, and created a new project in the same directory. I restored the files from the old project’s app directory, ran npm install again, and found that everything worked normally this time.

**Comment by NullVoxPopuli** [comment]
Glad you found a path to success!

For others, an update like this can be done more automatedly via:
```
pnpm dlx ember-cli@6.8 init . --name project-name
```
Usually ember-cli-update would also work:
```
pnpm dlx ember-cli-update 
```
