### ISSUE TITLE
`@glimmer/component` v2 is not working for ember < 4.10

### ISSUE THREAD

**Issue by mkszepp** [emberjs/ember.js#20790]
### 🐞 Describe the Bug
While whitelisting `@glimmmer/component` v2 in ember-basic-dropdown we have discoverd that isn't working in ember <= 4.8

The reason is that there was used  `@ember/owner` inside `@glimmer/components`: https://github.com/emberjs/ember.js/blob/main/packages/%40glimmer/component/src/index.ts#L5

Error:
`Error: Could not find module `@ember/owner` imported from ember-basic-dropdown/components/basic-dropdown`

CI error:
https://github.com/cibernox/ember-basic-dropdown/actions/runs/11777892189/job/32803253327?pr=941#step:6:202

The glimmer changelogs are telling ember < 3.13 is dropped see https://github.com/emberjs/ember.js/blob/main/packages/%40glimmer/component/CHANGELOG.md

**Comment by kategengler** [comment]
cc @ef4 I also think @glimmer/component is missing a README

**Comment by ijlee2** [comment]
On a related note, after updating `@glimmer/component` from `1.1.2` to `2.0.0` in a project with Glint, I saw type errors in components with `constructor()`:

```ts
import Component from '@glimmer/component';

interface MySignature {
  // ...
}

export default class MyComponent extends Component<MySignature> {
  constructor(owner: unknown, args: MySignature['Args']) {
    super(owner, args);

    // ...
  }
}
```

```sh
[lint:types] src/components/my-component.ts:31:11 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'Owner'.
[lint:types] 
[lint:types] 31     super(owner, args);
[lint:types]              ~~~~~
```

I was under the impression that writing `owner: unknown` is okay, since `owner` is an implementation detail of Ember. I feel like I might have also picked up `unknown` from official documentations or some Ember repo(s). For example, https://typed-ember.gitbook.io/glint/troubleshooting/diagnosing-common-error-messages#does-not-satisfy-the-constraint-invokable.

Can you help us clarify whether we should write `owner: Owner` instead, where the type `Owner` comes from `@ember/owner`, or if this might be a bug introduced in `2.0.0`?

**Comment by mkszepp** [comment]
we have seen the same error inside `ember-power-select` (1 usage was unknown)...

In additional i think we need a patch for current ember LTS versions, because `@glimmer/component` v2 is not whitelisted as peerDependency (i think for in v6 landed)

**Comment by mkszepp** [comment]
@ef4 `@ember/owner` was introduced in [4.10](https://github.com/emberjs/ember.js/blob/main/CHANGELOG.md#v4100-january-11-2023)

**Comment by simonihmig** [comment]
I can confirm, not possible to get this to work with Ember 4.8. See for example the linked PR above, all scenarios but 4.8 passing.

> We should probably just document that @glimmer/component 2.0 has Ember 4.8 as its oldest supported version.

That needs to be 4.10 then, or 4.12 as a former LTS.
